### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Robert-N7** [MakaylaHarris/CS4488_Project#28]
Start Date: ____________
Estimate: ______________
End Date: _____________

Dependencies: #27 Test project created

Validation Criteria:
- [ ] Write a unit test to add/remove dependency to a task.
- [x] Database should update to reflect dependency (and its removal).
- [ ] Dependent task should not start before it's parent.
- [x] If the parent task is not finished and the current date is past the start date of the dependent, the dependent's start and end date should shift forward.

**Comment by Moziki** [comment]
Estimated time: 5 hours
Actual time: 4 hours
