### ISSUE TITLE
Create Class Diagram for Database

### ISSUE THREAD

**Issue by marckade** [MakaylaHarris/CS4488_Project#7]
This includes Primary Keys, Dependencies, Relationships, etc. Anything needed to create the database

Date Started (In progress): 1/30/2021

Estimate for Completion: 1 day

Date Completed (In Done): 1/31/2021

**Comment by Moziki** [comment]
LINK TO DIAGRAMS
Make sure that no one can merge with master unless other team members have approved the pull request.
https://lucid.app/lucidchart/invitations/accept/f270e867-62dd-4937-b6fe-5765bc2c7374

**Comment by Robert-N7** [comment]
Created diagram that matches current database on develop branch (under Pert\Diagrams)
